[package]
name = "bone-collector"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[profile.dev.package."*"]
opt-level = 3

[profile.dev]
opt-level = 1

[dependencies]
bevy = "0.8"
bevy_rapier3d = { version = "0.16.1", features = [ "simd-stable", "debug-render" ] }
